
services:
  roamingbites:
    image: ${APP_IMAGE}
    container_name: roamingbites
    hostname: roamingbites
    environment:
      DB_HOST: postgres_primary
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: StrongPass123
      DB_NAME: myapp
      
      MINIO_ENDPOINT: http://minio1:9000
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: StrongPass123
      MINIO_BUCKET: roamingbites
      
      APP_PORT: 5000
      APP_DEBUG: "False"
      
      DB_CONNECTION_TIMEOUT: 5
      MINIO_CONNECTION_TIMEOUT: 5
    ports:
      - "5000:5000"
    networks:
      - db_minio_cluster
      - db_postgres_cluster
    volumes:
      - ./logs:/var/log
    restart: unless-stopped

networks:
  db_minio_cluster:
    external: true
  db_postgres_cluster:
    external: true
