- name: Create app directory
  file:
    path: /home/roamingbites/app
    state: directory

- name: Create app docker compose
  copy:
    src: .
    dest: /home/roamingbites/app

- name: Create app docker image
  command: docker build -t app-roamingbites:latest .
  args:
    chdir: /home/roamingbites/app

- name: Run app
  command: docker compose up -d
  args:
    chdir: /home/roamingbites/app
